//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Magenta.rc
//
#define MANIFEST_RESOURCE_ID            2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAGENTA_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define CG_IDS_PHYSICAL_MEM             104
#define CG_IDS_DISK_SPACE               105
#define CG_IDS_DISK_SPACE_UNAVAIL       106
#define IDS_READY                       107
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAGENTA                129
#define IDD_INPUTBOX                    132
#define IDD_PRIVATE_CHAT                133
#define IDD_CHAT_CONSOLE                134
#define IDD_SHOW_IGNORED                136
#define IDI_NORMAL                      138
#define IDI_CYAN                        139
#define IDI_GUEST                       140
#define IDD_OPTIONS                     141
#define IDD_STATUS_WINDOW               142
#define IDR_MENU_STATUS                 143
#define IDB_LOGO                        145
#define IDD_BLOCK_LIST                  146
#define IDD_AUTO_LOG_TYPE               148
#define IDD_URL_GRABBER                 149
#define IDD_SEARCH                      150
#define IDD_NAME_SLIDE                  151
#define IDD_BUG_REPORT                  153
#define IDR_ACCELERATOR_MAGENTA         154
#define IDD_ANNOTATION                  155
#define IDC_PHYSICAL_MEM                1000
#define IDC_STATIC_PHYS_MEM             1002
#define IDC_STATIC_FRAME                1004
#define IDC_STATIC_ABOUT                1005
#define IDC_CHAT                        1006
#define IDC_IGNORE                      1007
#define IDC_PRIVATE_CHAT                1008
#define IDC_SEND_PRIVATE                1009
#define IDC_SEND                        1010
#define IDC_STATIC_NAME                 1011
#define IDC_EDIT_NAME                   1012
#define IDC_PANEL                       1014
#define IDC_STATIC_WHO                  1015
#define IDC_LIST_REGULARS               1016
#define IDC_STATIC_CYAN                 1017
#define IDC_LIST_CYAN                   1018
#define IDC_SCRATCH                     1019
#define IDC_STATIC_ERROR                1020
#define IDC_STATIC_RAW_COMMAND          1022
#define IDC_EDIT_COMMAND                1023
#define IDC_RTF_PRIVATE_PANEL           1024
#define IDC_EDIT_PRIVATE_MSG            1025
#define IDC_PRIVATE_SEND                1026
#define IDC_PRIVATE_CLOSE               1027
#define IDC_PRIVATE_SAVE                1028
#define IDC_CONSOLE_SAVE                1030
#define IDC_CONSOLE_CLOSE               1031
#define IDC_CONSOLE_CLEAR               1032
#define IDC_RTF_CONSOLE                 1033
#define IDC_MESSAGE                     1035
#define IDC_UNIGNORE                    1036
#define IDC_LVW_IGNORED                 1037
#define IDC_FRAME_HOST                  1038
#define IDC_STATIC_HOSTNAME             1039
#define IDC_STATIC_PORT                 1040
#define IDC_EDIT_HOSTNAME               1041
#define IDC_EDIT_PORT                   1042
#define IDC_CHECK_MUTUAL                1043
#define IDC_CHECK_SEND_IGNORE           1044
#define IDC_CHECK_DISPLAY_IGNORE        1045
#define IDC_CHECK_NOTIFY                1046
#define IDC_LIST_STATUS                 1047
#define IDC_STATIC_STATUS               1048
#define IDC_STATIC_VERSION              1049
#define IDC_PIC_LOGO                    1050
#define IDC_STATIC_CONTACT              1053
#define IDC_FRAME_ABOUT                 1054
#define IDC_CHECK_CONSOLE               1055
#define IDC_BLOCK_ADD                   1056
#define IDC_EDIT_BLOCK_NAME             1057
#define IDC_BLOCK_REMOVE                1058
#define IDC_STATIC_BLOCK_NAME           1059
#define IDC_LIST_BLOCK                  1060
#define IDC_STATIC_BLOCK_LIST           1061
#define IDC_FRAME_LOGIN                 1062
#define IDC_CHECK_LOGIN                 1063
#define IDC_STATIC_USERNAME             1064
#define IDC_EDIT_USERNAME               1065
#define IDC_STATIC_OTHER_OPTS           1066
#define IDC_FRAME_CRASH                 1067
#define IDC_STATIC_SMTP                 1068
#define IDC_CHECK_CRASH                 1069
#define IDC_EDIT_SMTP                   1070
#define IDC_STATIC_RETURN               1072
#define IDC_EDIT_RETURN_EMAIL           1073
#define IDC_CHECK_CONNECT               1075
#define IDC_BUTTON1                     1076
#define IDC_COLOR                       1076
#define IDC_CHECK_CHATSERVER            1077
#define IDC_CHECK_AUTOSCROLL            1078
#define IDC_STATIC_OPTS                 1083
#define IDC_RADIO_TEXT                  1084
#define IDC_RADIO_HTML                  1085
#define IDC_RADIO_XML                   1086
#define IDC_AUTO_LOG                    1087
#define IDC_STATIC_URLS                 1088
#define IDC_LIST_URLS                   1089
#define IDC_EDIT_SEARCH_TEXT            1091
#define IDC_STATIC_SEARCH_TEXT          1092
#define IDC_EDIT_SEARCH_SNAP            1093
#define IDC_CHECK_BROWSE_NEW_WINDOW     1094
#define IDC_EDIT_NAME_SLIDE             1095
#define IDC_STATIC_DESCRIPTION          1096
#define IDC_EDIT_BUG                    1097
#define IDC_LIST_CONFIG                 1098
#define IDC_CHECK_HIDE_TRAY_ICON        1099
#define IDC_EDIT_INFO                   1100
#define IDC_CHECK_HOUR                  1101
#define IDC_STATIC_CURRENT_ANN          1102
#define IDC_EDIT_OLD_ANN                1103
#define IDC_STATIC_NEW_ANN              1104
#define IDC_EDIT_NEW_ANN                1105
#define ID_HELP_ABOUT                   32771
#define ID_CHAT_CONNECT                 32772
#define ID_CHAT_DISCONNECT              32773
#define ID_CHAT_SHOW_IGNORED            32774
#define ID_CHAT_SAVE_LOG                32775
#define ID_CHAT_CLEAR_CHAT_WINDOW       32776
#define ID_CHAT_EXIT                    32777
#define ID_TOOLS_OPTIONS                32778
#define ID_TOOLS_FONT                   32779
#define ID_TOOLS_STATUS_WINDOW          32780
#define ID_TOOLS_CONSOLE                32781
#define ID_TOOLS_SEND_RAW_COMMAND       32782
#define IDS_TIME_FORMAT                 32783
#define ID_STAT_FILE_SAVE               32784
#define ID_STAT_FILE_LOG                32785
#define ID_STAT_FILE_CLOSE              32786
#define ID_STAT_VIEW_ICON               32787
#define ID_STAT_VIEW_REPORT             32788
#define ID_BLOCK_LIST                   32789
#define ID_OPACITY_100                  32790
#define ID_OPACITY_90                   32791
#define ID_OPACITY_80                   32792
#define ID_OPACITY_70                   32793
#define ID_OPACITY_60                   32794
#define ID_OPACITY_50                   32795
#define ID_OPACITY_40                   32796
#define ID_OPACITY_30                   32797
#define ID_OPACITY_20                   32798
#define ID_OPACITY_10                   32799
#define ID_SAVE_FULL_LOG                32800
#define ID_LOGGING                      32801
#define ID_CLEAR_LOG                    32802
#define ID_HELP_WEBSITE                 32803
#define ID_HELP_TOPICS                  32804
#define ID_URL_GRABBER                  32805
#define ID_TOOLS_SEARCH                 32806
#define ID_SWITCH_NAME                  32807
#define ID_CHAT_SWITCH_NAME             32808
#define ID_TOOLS_ON_TOP                 32812
#define ID_FILE_ANNOTATE                32813
#define ID_TOOLS_ANNOTATE               32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
